{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stzteam.forgemini",
    "module": "ForgeMini",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeMini-1.0.7.jar",
          "url": "ForgeMini-1.0.7.jar",
          "size": 16433,
          "sha512": "e59c94d1328c1165ec9a4f8f9e1042ec32af9e8d69dc1c182cf72574e6175c5fb67baf95dcd93419a4d83bf5a310b5122430d34a8cf6b90d0ae152d8479ea4cc",
          "sha256": "0e3b6269bc50ed5ab4365695a0c2e1b730e545d8f55af11b67affcb11f0c9964",
          "sha1": "57a4d0069209df4e9112b54f899e8aef2dbe5233",
          "md5": "501d72fef8e40944d2ad86ff6d4798fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ForgeMini-1.0.7.jar",
          "url": "ForgeMini-1.0.7.jar",
          "size": 16433,
          "sha512": "e59c94d1328c1165ec9a4f8f9e1042ec32af9e8d69dc1c182cf72574e6175c5fb67baf95dcd93419a4d83bf5a310b5122430d34a8cf6b90d0ae152d8479ea4cc",
          "sha256": "0e3b6269bc50ed5ab4365695a0c2e1b730e545d8f55af11b67affcb11f0c9964",
          "sha1": "57a4d0069209df4e9112b54f899e8aef2dbe5233",
          "md5": "501d72fef8e40944d2ad86ff6d4798fd"
        }
      ]
    }
  ]
}
